---
- name: Install saslauthd, postfix, pip3, git
  apt:
    name:
      - postfix
      - postfix-pcre
      - sasl2-bin
      - python3-pip
      - git
    state: present
  become: true
  tags: apt

- name: Start and enable postfix
  systemd:
    name: postfix
    state: started
    enabled: true
  become: true

- name: Create sasl2 config folder
  file:
    dest: /etc/sasl2
    state: directory
    mode: 0755
  become: true

- name: Template postfix files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - src: main.cf.j2
      dest: /etc/postfix/main.cf
    - src: virtual.j2
      dest: /etc/postfix/virtual
    - src: smtpd.conf.j2
      dest: /etc/postfix/sasl/smtpd.conf
    - src: saslauthd-postfix.j2
      dest: /etc/default/saslauthd-postfix
  become: true
  notify:
    - Restart saslauthd
    - Restart postfix

- name: Configure saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: Restart saslauthd
  with_items:
    - regexp: "^START.*=.*$"
      line: "START=yes"
    - regexp: "^MECHANISMS.*=.*$"
      line: 'MECHANISMS="shadow"'
  become: true

- name: Add postfix user to sasl group
  user:
    name: postfix
    groups: sasl
    append: true
  become: true

- name: Register dpkg-statoveride list
  command: dpkg-statoverride --list /var/spool/postfix/var/run/saslauthd
  register: dpkg_statoveride
  ignore_errors: true
  changed_when: false

- name: Set dpkg-statoveride for saslauthd
  command: dpkg-statoverride --add root sasl 710 /var/spool/postfix/var/run/saslauthd
  notify:
    - Restart saslauthd
    - Restart postfix
  become: true
  when: dpkg_statoveride.stdout != "root sasl 710 /var/spool/postfix/var/run/saslauthd"

- name: Add telegram user and assign it to the mail group
  user:
    name: "{{ telegram_user }}"
    groups: mail
    append: true
  become: true

- name: Set telegram user password
  user:
    name: "{{ telegram_user }}"
    password: "{{ telegram_password_hash }}"
  become: true
  when: telegram_password_hash | default(false)

- name: Create mail file for telegram user
  file:
    state: touch
    path: "/var/spool/mail/{{ telegram_user }}"
    owner: "{{ telegram_user }}"
    group: mail
    modification_time: preserve
    access_time: preserve
    mode: 0660
  become: true

- name: Install email-to-telegram using pip
  pip:
    name: "email-to-telegram=={{ telegram_version }}"
  notify: Restart email-to-telegram
  become: true

- name: Create config directory
  file:
    path: "{{ telegram_config_directory }}"
    state: directory
  become: true

- name: Template config.ini for email-to-telegram
  template:
    src: config.ini.j2
    dest: "{{ telegram_config_directory }}{{ telegram_config_file }}"
    owner: "{{ telegram_user }}"
    mode: 0600
  notify: Restart email-to-telegram
  become: true

- name: Template email-to-telegram service
  template:
    src: email-to-telegram.service.j2
    dest: /etc/systemd/system/email-to-telegram.service
  notify: Restart email-to-telegram
  become: true

- name: Start and enable email-to-telegram
  systemd:
    name: email-to-telegram
    state: started
    enabled: true
  become: true
