- name: Install saslauthd and postfix
  apt:
    name:
      - postfix
      - sasl2-bin
    state: present

- name: Postfix started and enabled
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: Create sasl2 folder
  file:
    dest: /etc/sasl2
    state: directory

- name: Copy smtpd.conf
  copy:
    src: smtpd.conf
    dest: /etc/postfix/sasl/smtpd.conf
  notify: Restart postfix

- name: Configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  notify: Restart postfix
  with_items:
    - { regexp: "smtpd_sasl_path.*=.*$", line: "smtpd_sasl_path = smtpd" }
    - {
        regexp: "smtpd_sasl_auth_enable.*=.*$",
        line: "smtpd_sasl_auth_enable = yes",
      }
    - { regexp: "myorigin.*=.*$", line: "myorigin = localhost.localdomain" }
    - {
        regexp: "mydestination.*=.*$",
        line: "mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain, localhost.localdomain",
      }

- name: Configure saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  notify: Restart saslauthd
  with_items:
    - { regexp: "^START.*=.*$", line: "START=yes" }
    - { regexp: "^MECHANISMS.*=.*$", line: 'MECHANISMS="shadow"' }

- name: Add postfix to sasl group
  user:
    name: postfix
    groups: sasl
    append: "yes"

- name: Copy fix-saslauthd.sh
  copy:
    src: fix-saslauthd.sh
    dest: /opt/
    mode: "0744"
  notify: Restart postfix

- name: Start postfix and run fix-saslauthd script on reboot
  cron:
    name: "Fixes saslauthd run directory"
    special_time: reboot
    job: "/opt/fix-saslauthd.sh"

- name: Mail folder is writeable
  file:
    dest: /var/mail
    mode: "777"
    state: directory
