---
- name: Install saslauthd, postfix, pip3, git
  apt:
    name:
      - postfix
      - postfix-pcre
      - sasl2-bin
      - python3-pip
      - git
    state: present
  become: true
  tags: apt

- name: Start and enable postfix
  service:
    name: postfix
    state: started
    enabled: true
  become: true

- name: Create sasl2 config folder
  file:
    dest: /etc/sasl2
    state: directory
  become: true

- name: Copy postfix files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: main.cf
      dest: /etc/postfix/main.cf
    - src: virtual
      dest: /etc/postfix/virtual
    - src: smtpd.conf
      dest: /etc/postfix/sasl/smtpd.conf
  become: true
  notify: Restart postfix

- name: Configure saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: Restart saslauthd
  with_items:
    - regexp: "^START.*=.*$"
      line: "START=yes"
    - regexp: "^MECHANISMS.*=.*$"
      line: 'MECHANISMS="shadow"'
  become: true

- name: Add postfix user to sasl group
  user:
    name: postfix
    groups: sasl
    append: true
  become: true

- name: Copy fix_saslauthd.sh script
  copy:
    src: fix_saslauthd.sh
    dest: /opt/
    mode: "0755"
  notify:
    - Run fix saslauthd script
    - Restart postfix
  become: true

- name: Run fix_saslauthd script on reboot
  cron:
    name: Fixes saslauthd run directory
    special_time: reboot
    job: /opt/fix_saslauthd.sh
  become: true

- name: Add telegram user and assign it to the mail group
  user:
    name: telegram
    groups: mail
    append: true
  become: true

- name: Set telegram password
  user:
    name: telegram
    password: "{{ telegram_password_hash }}"
  become: true
  when: telegram_password_hash | default(false)

- name: Create mail file for telegram user
  file:
    state: touch
    path: /var/spool/mail/telegram
    owner: telegram
    group: mail
    modification_time: preserve
    access_time: preserve
    mode: "0660"
  become: true

- name: Install email-to-telegram git version via pip
  pip:
    name: git+https://github.com/ItsNotGoodName/email-to-telegram.git
    state: latest
  notify: Restart email-to-telegram
  become: true

- name: Create email-to-telegram config directory
  file:
    path: /etc/email-to-telegram/
    state: directory
  become: true

- name: Copy config.ini for email-to-telegram
  template:
    src: config.ini.j2
    dest: /etc/email-to-telegram/config.ini
    owner: telegram
    mode: "0600"
  notify: Restart email-to-telegram
  become: true

- name: Copy email-to-telegram service
  template:
    src: email-to-telegram.service.j2
    dest: /etc/systemd/system/email-to-telegram.service
  notify: Restart email-to-telegram
  become: true

- name: Start and enable email-to-telegram
  systemd:
    name: email-to-telegram
    state: started
    enabled: true
  become: true
