- name: Install saslauthd, postfix, pip3, git
  package:
    name:
      - postfix
      - sasl2-bin
      - python3-pip
      - git
    state: present

- name: Start and enable postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Create sasl2 config folder
  file:
    dest: /etc/sasl2
    state: directory

- name: Copy smtpd.conf
  copy:
    src: smtpd.conf
    dest: /etc/postfix/sasl/smtpd.conf
  notify: Restart postfix

- name: Copy main.cf
  copy:
    src: main.cf
    dest: /etc/postfix/main.cf 
  notify: Restart postfix

- name: Configure saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  notify: Restart saslauthd
  with_items:
    - { regexp: "^START.*=.*$", line: "START=yes" }
    - { regexp: "^MECHANISMS.*=.*$", line: 'MECHANISMS="shadow"' }

- name: Add postfix user to sasl group
  user:
    name: postfix
    groups: sasl
    append: "yes"

- name: Copy fix_saslauthd.sh script
  copy:
    src: fix_saslauthd.sh
    dest: /opt/
    mode: "0744"
  notify: Restart postfix
  register: copy_fix_saslauthd
  when: ansible_distribution == 'Debian'

- name: Run fix_saslauthd script on reboot
  cron:
    name: "Fixes saslauthd run directory for debian"
    special_time: reboot
    job: "/opt/fix_saslauthd.sh"
  when: ansible_distribution == 'Debian'

- name: Run fix_saslauthd script
  command: /opt/fix_saslauthd.sh
  when: ansible_distribution == 'Debian' and copy_fix_saslauthd.changed

- name: Add telegram user and assign it to the mail group
  user:
    name: telegram
    group: mail

- name: Install email-to-telegram git version via pip
  pip:
    name: git+https://github.com/ItsNotGoodName/email-to-telegram.git

- name: Create email-to_telegram config directory
  file:
    path: /etc/email-to-telegram/
    state: directory

- name: Copy config.ini for email-to-telegram
  template:
    src: config.ini
    dest: /etc/email-to-telegram/config.ini
    owner: telegram
    mode: '0600'
