- name: Install saslauthd and postfix
  package:
    name:
      - postfix
      - sasl2-bin
    state: present

- name: Start and enable postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Create sasl2 config folder
  file:
    dest: /etc/sasl2
    state: directory

- name: Copy smtpd.conf
  copy:
    src: smtpd.conf
    dest: /etc/postfix/sasl/smtpd.conf
  notify: Restart postfix

- name: Copy main.cf
  copy:
    src: main.cf
    dest: /etc/postfix/main.cf 
  notify: Restart postfix

- name: Configure saslauthd
  lineinfile:
    path: /etc/default/saslauthd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  notify: Restart saslauthd
  with_items:
    - { regexp: "^START.*=.*$", line: "START=yes" }
    - { regexp: "^MECHANISMS.*=.*$", line: 'MECHANISMS="shadow"' }

- name: Add postfix user to sasl group
  user:
    name: postfix
    groups: sasl
    append: "yes"

- name: Copy fix-saslauthd.sh script
  copy:
    src: fix-saslauthd.sh
    dest: /opt/
    mode: "0744"
  notify: Restart postfix
  when: ansible_distribution == 'Debian'

- name: Run fix-saslauthd script on reboot
  cron:
    name: "fixes saslauthd run directory for debian"
    special_time: reboot
    job: "/opt/fix-saslauthd.sh"
  when: ansible_distribution == 'Debian'

- name: Add telegram user and assign it to the mail group
  user:
    name: telegram
    group: mail
